name = "auction-central-svg-rasterizer"
workers_dev = false
preview_urls = false
compatibility_date = "2026-08-12"
main = "build/worker/shim.mjs"

[build]
command = "worker-build --release"

[[rules]]
globs = [ "**/*.wasm" ]
type = "CompiledWasm"
fallthrough = false
